### ISSUE TITLE
Auto-complete doesn't geocode addresses or show suggestions

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/modeify#130]
On Android phones. Need to listen to other input events.

**Comment by demory** [comment]
I have not been able to reproduce on my phone; both the drop-down and geocoding are working as expected. I am running Android 4.4.2 w/ Chrome 39.0.2171.93. Do we know anything else about the user's setup?

![image](https://cloud.githubusercontent.com/assets/653100/5633599/f5237856-95a6-11e4-938f-ebd4b50d35b7.png)

![image](https://cloud.githubusercontent.com/assets/653100/5633633/524d6b90-95a7-11e4-85ee-dbb8db78cb83.png)

**Comment by trevorgerhardt** [comment]
This is an old ticket, I'm going to close and we can open a new one if we see it again.
