### ISSUE TITLE
Relevant walk-to-transit trips lost due to limit parameter

### ISSUE THREAD

**Issue by demory** [conveyal/modeify#163]
In the following example, bike-to-transit trips crowd out a quality one-seat walk-to-transit trip (the ART 41; disable biking to show) due to the default limit of 3. In such cases the profile router should return at least one valid walk-to-transit trip.

http://www.carfreeatoz.com/planner?from=5000%20Columbia%20Pike%2C%20Arlington%2C%20Virginia%2C%20USA&to=2020%2014th%20St%20N%2C%20Arlington%2C%20Virginia%2C%20USA&modes=BICYCLE%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F

**Comment by trevorgerhardt** [comment]
@abyrd this issue creeps up in a few different places and I think it's a high priority to tackle. When you get a chance I was wondering if you could comment on the timeline or let me know if we need to figure out more details of the implementation.

**Comment by abyrd** [comment]
This has been resolved in OTP. The limit parameter now applies to each access mode separately.
