### ISSUE TITLE
Page does not load in IE9; no browser compatibility warning

### ISSUE THREAD

**Issue by demory** [conveyal/modeify#175]
![image](https://cloud.githubusercontent.com/assets/653100/5985690/8fb9ef52-a8b3-11e4-8b3b-6cf2978c0e13.png)

**Comment by trevorgerhardt** [comment]
This should be fixed in the latest, can you check @demory?

**Comment by trevorgerhardt** [comment]
This should be fixed in the latest, can you check @demory?
