### ISSUE TITLE
Vertically align CaBi icon

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/modeify#198]
Is it offset vertically a bit? Since we're making them all fit in 20x20 I'd prefer it if they were all vertically and horizontally aligned inside their respective frame.

![screenshot 2015-03-25 18 37 58](https://cloud.githubusercontent.com/assets/776780/6837019/1560d474-d31e-11e4-9e3b-f77e6afe1c04.png)

![screenshot 2015-03-25 18 39 02](https://cloud.githubusercontent.com/assets/776780/6837029/3b7a60bc-d31e-11e4-97d9-8e5f99a41779.png)

**Comment by kchanba** [comment]
Sure I will align all to top and left

**Comment by trevorgerhardt** [comment]
Ah, I should've specified. If prefer if they were centered vertically and horizontally.
