### ISSUE TITLE
Bikeshare result shows start station but not end

### ISSUE THREAD

**Issue by demory** [conveyal/modeify#206]
http://localhost:5000/planner?from=4631%2014th%20St%20N%2C%20Arlington%2C%20Virginia&to=1701%20N%20Kent%20St%2C%20Arlington%2C%20Virginia&modes=BICYCLE_RENT%2CWALK&start_time=7&end_time=9&days=M%E2%80%94F

I believe this is an issue in the OTP narrative generator; will investigate

**Comment by trevorgerhardt** [comment]
In case you need to update the narrative directions on the client side: https://github.com/conveyal/modeify/blob/master/client/route-directions-table/index.js#L118
