### ISSUE TITLE
Transitive crash

### ISSUE THREAD

**Issue by mattwigway** [conveyal/modeify#209]
When making [this trip](http://www.carfreeatoz.com/planner?from=1634%20Eckington%20Pl%20NE%2C%20Washington%2C%20District%20of%20Columbia&to=1500%20Wilson%20Blvd%2C%20Arlington%2C%20Virginia%2C%20USA&modes=BICYCLE%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F) (after dragging the pin) on production, I get "Uncaught TypeError: Cannot read property 'x' of undefined on build.js line 17." The transitive overlay then disappears from the map.

Chrome 41 on Ubuntu.

**Comment by trevorgerhardt** [comment]
Doesn't appear to be an issue any longer. Closing for now.
