### ISSUE TITLE
Rush plus options for Yellow line are missing

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#235]
[here is the route] (http://carfreeatoz.com/planner?from=719%20S%20Adams%20St%2C%20Arlington%2C%20Virginia&to=4700%20River%20Rd%2C%20Riverdale%20Park%2C%20Maryland&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)

**Comment by trevorgerhardt** [comment]
That route is showing Yellow the whole way for 7-9am, which is the rush plus option. Other times throughout the day you won't see Yellow the whole way show up as an option (http://carfreeatoz.com/planner?from=719%20S%20Adams%20St%2C%20Arlington%2C%20Virginia&to=4700%20River%20Rd%2C%20Riverdale%20Park%2C%20Maryland&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=10&end_time=11&days=M%E2%80%94F)
