### ISSUE TITLE
Include Metroway routes 

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#240]
Don't see Metroway in [this route] (http://carfreeatoz.com/planner?from=2500%20Terrett%20Ave%2C%20Alexandria%2C%20Virginia&to=911%20V%20St%20NW%2C%20Washington%2C%20District%20of%20Columbia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)

http://metrowayva.com/

**Comment by trevorgerhardt** [comment]
They don't have GTFS and seem pretty to be a pretty minimal provider of any type. Did Arlington request them to be included? We would need to work with them directly to get their data, so it's not an issue that should be discussed here, probably in Basecamp instead.
