### ISSUE TITLE
Improve D6 Route

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#248]
User normally rides the D6 picking up half a block from start location and it is not appearing in [this example] (http://carfreeatoz.com/planner?from=1233%20C%20St%20NE%2C%20Washington%2C%20District%20of%20Columbia&to=3336%20M%20St%20NW%2C%20Washington%2C%20District%20of%20Columbia&modes=BUS%2CWALK&start_time=7&end_time=9&days=M%E2%80%94F)

[Here is the schedule] (https://www.wmata.com/bus/timetables/dc/d5-6.pdf)

**Comment by trevorgerhardt** [comment]
Hmmm it appears like the D6 portion of the route does pick up half a block from the start location in the route given right? Am I seeing it wrong?
