### ISSUE TITLE
Improve Key Bridge bike routing, take Roosevelt Bridge instead

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#250]
– This isn't a good option, because it requires carrying the bike on stairs to go from Key Bridge to the C&O path. When I bike between these two locations, I usually take the Roosevelt Bridge, because traffic on M St. makes biking through Georgetown difficult.

Another comment regarding Key Bridge:
– Stay on Canal and go over Key Bridge take a left over Ft. Myer onto Custiis Trail or stay on Capital Cresent Trail to Rock Creek path to Ohio Drive over 395 Bridge to Mount Vernon Trail.

**Comment by trevorgerhardt** [comment]
Are stairs listed on segments in OSM? We could list them as impassable if they are. Do we have routes associated with this?

**Comment by kchanba** [comment]
[Here] (http://carfreeatoz.com/planner?from=-77.07960493411963,38.89627578390139&to=-77.04165568506102,38.90315951500071&modes=BICYCLE,BICYCLE_RENT,BUS,TRAINISH,WALK,CAR&start_time=7&end_time=9&days=M%E2%80%94F) is the route associated

**Comment by trevorgerhardt** [comment]
I biked this route before. People have their opinions about it, but this is a pretty straightforward and safe way to go. I wouldn't recommend any changes.

http://carfreeatoz.com/planner?from=1860%20N%20Scott%20St%2C%20Arlington%2C%20Virginia&to=1015%2018th%20St%20NW%2C%20Washington%2C%20District%20of%20Columbia&modes=BICYCLE%2CBICYCLE_RENT%2CWALK&start_time=7&end_time=9&days=M%E2%80%94F
