### ISSUE TITLE
Improve routes to Bethesda

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#251]
– G'town to Bethesda- should be 30's bus to Tenleytown & then red line, not 30's up to F'ship Hts & then red line

– Bad. Makes more sense to use the CCT from SS to Bethesda instead of going so far north to use Beach

**Comment by trevorgerhardt** [comment]
Without a route to look at this information isn't enough as this could just be a user opinion about their own route which could be wrong.

**Comment by kchanba** [comment]
[here is the route] (http://carfreeatoz.com/planner?from=-77.09907849667451,38.990768653851376&to=-77.06890714944461,38.917210439910946&modes=BICYCLE,BICYCLE_RENT,BUS,TRAINISH,WALK,CAR&start_time=7&end_time=9&days=M%E2%80%94F)

**Comment by trevorgerhardt** [comment]
We show both options: http://carfreeatoz.com/planner?from=4800%20Auburn%20Ave%2C%20Bethesda%2C%20Maryland&to=2101%20Wisconsin%20Ave%20NW%2C%20Washington%2C%20District%20of%20Columbia&modes=BUS%2CTRAINISH%2CWALK&start_time=7&end_time=9&days=M%E2%80%94F
