### ISSUE TITLE
Improve bike speeds/preferences

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#263]
– Why do you think it would take 61 minutes to ride a bicycle 8.8 miles?!? The route you show takes me as little as 35 minutes - 40 is a good average. I understand allowing for experience/fitness but that is a really slow pace.

– bike speed assumptions are terribly slow which might demotivate potential riders. On my bike commute, biking takes no more time than either 2 seat public transport or driving

**Comment by trevorgerhardt** [comment]
This could be a whole interface discussion. We've made choices based on feedback from both sides. Some people saying it's too fast, others it's too slow. What would we want to change to support both sides? Do we want to support both sides or is there one that's highly represented that we should default to? (Which I believe is what we currently do)

**Comment by kchanba** [comment]
Per the feedback comments, the routes have been too slow (3-4 mentions). I have not seen any comments that say they are too fast. I think as we develop the user profile, emphasis should be placed on personalized bike speed. We have this feature built in the first iteration and should expand on it.

**Comment by trevorgerhardt** [comment]
User's can set their speed in the profile or by changing it inline in the scorer and re-run the search. We could try other places for them to change that setting, but I'd rather keep it unobtrusive. Increasing the default speed would prioritize biking even more and from my range of searches around the area our default bike speed is pretty accurate.

Also, chances are that the feedback came from consistent bikers. So while showing a slower time may demotivate potential riders, I'd guess that it's more accurate overall.

**Comment by trevorgerhardt** [comment]
More accurate to the range of people that will be using Modeify. Both bikers and non-bikers.
