### ISSUE TITLE
Improve transit and bike route for: 4555 Overlook Ave, SW, DC, to 6a E Mason Ave, Alexandria

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#268]
fails to find my actual transit commute (W5 bus > M Green > M Yellow > bike). 

– the bike commute option shows me exiting the Wilson Bridge Trail in VA well west of Washington St. That can't be done without jumping off the bridge (not recommended).

**Comment by trevorgerhardt** [comment]
Is there a route associated with this?

**Comment by kchanba** [comment]
[Here is the route] (http://carfreeatoz.com/planner?from=1%20E%20Mason%20Ave%2C%20Alexandria%2C%20Virginia&to=4401%20Overlook%20Ave%20SW%2C%20Washington%2C%20District%20of%20Columbia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)

**Comment by trevorgerhardt** [comment]
I'm not seeing either of these problems. The transit routes are specific to commuting times so if you are going in the right direction at the right time both ways get you the W5 / Green / Yellow pattern.

Also, the bridge does have exits right on either side for bike/ped (if I remember correctly) and that's what our route shows.
