### ISSUE TITLE
Improve route:  Orange, 623/621, 1C/2B via VIENNA METRO STATION, OX RD W & POST FOREST DR

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#274]
– It doesn't make sense to transfer from the 623 to the 2B at West Ox and Post Forest. The 2B leaves from Vienna Metro and even though it is a longer trip time wise, it avoids a transfer.

**Comment by trevorgerhardt** [comment]
Is there a route associated with this?

**Comment by kchanba** [comment]
Here is the [route] (http://carfreeatoz.com/planner?from=3900%20N%20Fairfax%20Dr%2C%20Arlington%2C%20Virginia&to=4951%20Alliance%20Dr%2C%20Fairfax%2C%20Virginia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)
