### ISSUE TITLE
Omit unreasonably short CaBi trips

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#275]
– changing from Red to Green/Yellow and then CaBi from Shaw to save 1 minute is probably not worthwhile either :)

**Comment by trevorgerhardt** [comment]
Example?

**Comment by kchanba** [comment]
[here is the route] (http://carfreeatoz.com/planner?from=1919%20Gayfields%20Dr%2C%20Silver%20Spring%2C%20Maryland&to=1769%20Church%20St%20NW%2C%20Washington%2C%20District%20of%20Columbia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)

**Comment by trevorgerhardt** [comment]
It's potentially a back up route in case the you want to avoid too much red line, also not unreasonably short.
