### ISSUE TITLE
Missing 96 and 97 Metrobus routes

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#276]

**Comment by kchanba** [comment]
![screen shot 2015-07-21 at 5 51 32 pm](https://cloud.githubusercontent.com/assets/2378745/8813390/33aa2dee-2fd1-11e5-912b-d3626e4220e8.png)
![screen shot 2015-07-21 at 5 51 49 pm](https://cloud.githubusercontent.com/assets/2378745/8813391/33b8c21e-2fd1-11e5-9504-9b489f42d543.png)

**Comment by trevorgerhardt** [comment]
If you turn off train you'll see the bus options. They don't show up because they're > 10 minutes slower than the train options.
