### ISSUE TITLE
Missing MetroExtra route: H11, Green, Orange/Silver/Blue via BUS & NAYLOR STATION RD, L'ENFANT PLAZA METRO STATION

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#278]
– The H11 + the 39 MetroExtra is almost always a better route than this because it not only takes around the same amount of time, it is much, much cheaper.

**Comment by kchanba** [comment]
We are not showing the MetroExtra 39 at Naylor Road Metro Station going into DC
 ![screen shot 2015-07-21 at 5 40 48 pm](https://cloud.githubusercontent.com/assets/2378745/8813214/ad110a7e-2fcf-11e5-8469-266a860c18a6.png)

![screen shot 2015-07-21 at 5 42 01 pm](https://cloud.githubusercontent.com/assets/2378745/8813248/e7aa7396-2fcf-11e5-8f10-cd0ce87075b6.png)

**Comment by trevorgerhardt** [comment]
Hmm with those routes it doesn't seem like the 39 would be appropriate. https://www.wmata.com/bus/timetables/DC/39.pdf

P.S. @kchanba please include links along with the images!
