### ISSUE TITLE
Improve route: routes Silver, 424 via TYSONS CORNER METRO STATION

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#279]
– take Metro all the way to the Spring Hill Station instead of getting off metro and taking a bus to Spring Hill.

**Comment by kchanba** [comment]
![screen shot 2015-07-21 at 5 12 08 pm](https://cloud.githubusercontent.com/assets/2378745/8812729/e671d70c-2fcb-11e5-912e-172f80030332.png)

Perhaps we should favor Silver line above buses in this area. As I move the start/end markers around in this area, the 494 and 405 bus rise to the top of the results panel when the silver line seems to be a viable option.

**Comment by trevorgerhardt** [comment]
We show the Silver line lower because it costs $500 more per year. We may want to make the colors differ from each other depending on the savings to emphasize that.
