### ISSUE TITLE
Add in parking lot info? 

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#280]
– PR lot holds 400plus cars and driving to the 902 is much safer due to narrow, windy roads. Why isn't that an option?

**Comment by trevorgerhardt** [comment]
What's the route associated with this? Without that information finding which lot they are referring to would be tough.

**Comment by kchanba** [comment]
There was not a route associated with this comment, but I think it's a general question about how we address parking information. I will add this to Basecamp as a feature to explore.
