### ISSUE TITLE
Imply traffic information in travel times

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#284]
Though we don't have specific traffic information, we may be able to make more accurate inferences on travel time based on rush-hour assumptions. This has come up in some feedback comments.

**Comment by trevorgerhardt** [comment]
For car trips we do show two times — bottom one is "without traffic", and the top one is our traffic estimation of 1.4 * without.

**Comment by kchanba** [comment]
Maybe we should highlight this more. Will develop a mock
