### ISSUE TITLE
Camden Yard stop on MARC not included in options

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#291]
http://carfreeatoz.com/planner?from=1527%2030th%20St%20NW%2C%20Washington%2C%20District%20of%20Columbia&to=650%20W%20Baltimore%20St%2C%20Baltimore%2C%20Maryland&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F

**Comment by trevorgerhardt** [comment]
Hmmm I'm not seeing the MARC at all in that link, just Amtrak. Removing biking makes the MARC appear. I'm not that familiar with the MARC train, but I just used the MTA trip planner and it gave a similar route to ours.
