### ISSUE TITLE
Bikeshare bikes and docks availables

### ISSUE THREAD

**Issue by jpizarrom** [conveyal/modeify#312]
Show extra info in the bike station like:

Client Side

- [ ] Bikes Available :2
- [ ] Docks Available :21
- [ ] Total Docks :23
- [ ] Hours Of Operation :06:00 - 23:00

OTP
- [ ] ?

**Comment by trevorgerhardt** [comment]
If there's a lightweight UI implementation that you'd like to take the time to connect with the station information than I would gladly review! If not, I'll close for now.
