### ISSUE TITLE
No results for trip to Warren County, VA

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#327]
No results for trip
http://www.carfreeatoz.com/planner?from=-78.26219301369582,38.84684120036218&to=-77.03256901154987,38.904706955962354&modes=BICYCLE,BICYCLE_RENT,BUS,TRAINISH,WALK,CAR&start_time=7&end_time=9&days=M%E2%80%94F

**Comment by trevorgerhardt** [comment]
That's out of our range, so we should show that, not just let the spinner keep going. Looks like there's some kind of error.
