### ISSUE TITLE
CFAZ Log In Not Functioning

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#328]
This could be a stormpath issue as I'm having trouble with my login as well. Message from NeoNiche:

> I hope you’re well. A few of us in the office just tried to log into our accounts on Car Free A to Z, and the site is not saving our accounts and, obviously, our saved addresses. I am clicking on Profile on the top right then Log In Here in Your Settings. Nothing happens. Could you please check into this? Thank you.
> 
> Regards,
> 
> Mark

**Comment by trevorgerhardt** [comment]
Ooff, this looks like a problem from the Stormpath Express library upgrade. Might have differences in configuration. Looking into it now.

**Comment by trevorgerhardt** [comment]
Fixed with 0211320140d8e9004488cf6527e24dcf55116d2c
