### ISSUE TITLE
Is MARC included?

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#330]
I don't see any transit options coming from Baltimore, Joe also mentions 'Joe again, I forgot one item: CFAZ says transit fare from Baltimore is $2.40. That might be Metro fare only. MARC fare is $8.00. If some fares aren't in the system, maybe there could be a way for users to enter missing fare data themselves.'

http://www.carfreeatoz.com/planner?from=919%20Argonne%20Drive%2C%20Baltimore%2C%20MD%2C%20Baltimore%2C%20Maryland&to=Miracles%2C%20Arlington%2C%20VA%2C%20Arlington%2C%20Virginia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F

**Comment by trevorgerhardt** [comment]
We include MARC. The route linked above is really far and may not fit into a given time window that we're searching for. Here it is in Google Maps: https://www.google.com/maps/dir/919+Argonne+Dr,+Baltimore,+MD+21218,+USA/Miracles,+1501+Wilson+Boulevard,+Arlington,+VA+22209,+United+States/@39.1028336,-77.0309521,11z/data=!4m14!4m13!1m5!1m1!1s0x89c8050f447fa88b:0x7693bb621b0bd543!2m2!1d-76.6019173!2d39.3382151!1m5!1m1!1s0x89b7b65c01ef04e1:0xc129b1a693d69fd1!2m2!1d-77.074208!2d38.8952468!5i2

@abyrd or @demory would know more about why we're not seeing this route.

**Comment by trevorgerhardt** [comment]
MARC in general, is included
