### ISSUE TITLE
Trip not allowing for walk to Metro

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#331]
Changed the walk time settings but it's still not showing it, Google claims it is a 21 minute walk:

[Live CFAZ](http://www.carfreeatoz.com/planner?from=1009%20Lincoln%20Avenue%2C%20Falls%20Church%2C%20VA%2C%20Falls%20Church%2C%20Virginia&to=Christian%20Science%20Reading%20Room%2C%20Washington%2C%20DC%2C%20Washington%2C%20Washington%2C%20D.C.&modes=TRAINISH%2CWALK&start_time=7&end_time=9&days=M%E2%80%94F)

[Google](https://www.google.com/maps/dir/1009+Lincoln+Ave,+Falls+Church,+VA+22046/Christian+Science+Reading+Room,+1250+I+Street+Northwest+%23102,+Washington,+DC+20005/@38.8917624,-77.1792194,12z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89b7b4daa3422469:0x4c072b570fec7f86!2m2!1d-77.182388!2d38.892843!1m5!1m1!1s0x89b7b79748615457:0xc0bb5d640febbe1b!2m2!1d-77.0293261!2d38.9012049!3e3)

**Comment by trevorgerhardt** [comment]
Turn up the walk time to anything over 20 and it works.
