### ISSUE TITLE
 1500 Pennsylvania Avenue, NW, Washington, DC (Whitehouse) showing up in Baltimore

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#333]
http://www.carfreeatoz.com/planner?from=%201500%20Pennsylvania%20Avenue%2C%20NW%2C%20Washington%2C%20DC&to=National%20Institutes%20of%20Health%20Fire%20Department%20Station%2051%2C%20Bethesda%2C%20MD%2C%20Bethesda%2C%20Maryland&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F

**Comment by kchanba** [comment]
Got a reminder from NeoNiche to get this corrected, they're using the address in presentations and being re-routed to Baltimore.

**Comment by trevorgerhardt** [comment]
@kchanba I'll take a look but, in the mean time, tell them to use the actual White House address (1600 Pennsylvania Ave) or type "White House". Both those work :smiley:

**Comment by kchanba** [comment]
@trevorgerhardt thanks! will do

**Comment by kchanba** [comment]
Apparently 'White House' works but '1600 Pennsylvania Ave' gets sent to Baltimore as well
![image](https://cloud.githubusercontent.com/assets/2378745/13990404/86d13f50-f0ea-11e5-8c43-c2d7e9f6bc58.png)
@trevorgerhardt

**Comment by trevorgerhardt** [comment]
Added the postal code to all search result text. Pelias does not weight POIs....we may want to spend some time helping them out.
