### ISSUE TITLE
Modals have (disabled) vertical scrollbars that interfere with layout

### ISSUE THREAD

**Issue by demory** [conveyal/modeify#340]
![screen shot 2016-05-26 at 4 58 10 pm](https://cloud.githubusercontent.com/assets/653100/15589931/0a00569a-2363-11e6-8e73-ca695093ab34.png)

**Comment by trevorgerhardt** [comment]
Cannot reproduce locally. (but did fix that button bug)

**Comment by trevorgerhardt** [comment]
Is this still a problem @demory ?
