### ISSUE TITLE
Stormpath Joined Okta

### ISSUE THREAD

**Issue by comlaterra** [conveyal/modeify#401]
Since it is not possible to register to Stormpath anymore, maybe it is a good idea to change the authentication management to [Okta](http://developer.okta.com/code/javascript/okta_auth_sdk) ?

**Comment by evansiroky** [comment]
I'm working on a branch that will use [Auth0](https://auth0.com) as the authentication provider.

**Comment by evansiroky** [comment]
Fixed with #411
