### ISSUE TITLE
missing nearby drive to transit options when bus enabled

### ISSUE THREAD

**Issue by kpwebb** [conveyal/modeify#82]
This trip trip shows nearby drive to transit options:

http://arlington.dev.conveyal.com/planner?from=2527%20Farmcrest%20Dr%2C%20Oak%20Hill%2C%20Virginia%2020171&to=1212%20Florida%20Ave%20NW%2C%20Washington%2C%20District%20of%20Columbia%2020009&modes=TRAINISH%2CWALK%2CCAR&start_time=8&end_time=9&days=M%E2%80%94F

Turning on the bus option causes the nearest drive to transit option to fall off the list:

**Comment by trevorgerhardt** [comment]
This problem no longer exists.
